### ISSUE TITLE
error 406

### ISSUE THREAD

**Issue by barsh** [barsh/SauleStarter#1]
Error 406 when browsing to API in Chrome.

![image](https://user-images.githubusercontent.com/2644202/37880076-9e70ee4a-3048-11e8-8c81-9430837dec20.png)

### Repro
1. clone this repo
2. open `SaulStarter.sln` in Visual Studio
2. [uncomment this line](https://github.com/barsh/SauleStarter/blob/master/SauleStarter/Controllers/CompaniesController.cs#L12)
3. Press F5
4. navigate to `/api/companies` in Chrome

**Comment by joukevandermaas** [comment]
This seems to be related to https://github.com/joukevandermaas/saule/issues/100 . What version of Saule are you using?

**Comment by barsh** [comment]
@joukevandermaas, Yes, I agree.  This project is using the latest release: 
[v1.6.0.373](https://github.com/barsh/SauleStarter/blob/master/SauleStarter/packages.config#L13)

but it appears the changes referenced in that issue haven't made it into a release yet.

**Comment by joukevandermaas** [comment]
@barsh please try a pre-release and see if that works for you.

**Comment by barsh** [comment]
@joukevandermaas good news.

With Saule beta-1.7.0.516, I no longer get HTTP error 406 when browsing `/api/companies`.  However, the response is XML instead of JSON API:
![image](https://user-images.githubusercontent.com/2644202/37972213-7204cb3c-319d-11e8-8003-14b6166cacaf.png)

Curiously, sending a request to that URL endpoint using [PostMan](https://www.getpostman.com/), I get a JSON API response:
![image](https://user-images.githubusercontent.com/2644202/37972320-b22163c4-319d-11e8-9e02-cca8d418bb3d.png)

What needs to be changed to get a JSON API response from Chrome?

**Comment by joukevandermaas** [comment]
How are you configuring Saule in your startup code? You should make sure its formatter is at the front of the list. By default, this is not the case unless you add JSON API to your `Accept` header. You can force it by using a different overload of the `ConfigureJsonApi` method.

**Comment by barsh** [comment]
Like this
```
config.ConfigureJsonApi();
```

See https://github.com/barsh/SauleStarter/blob/master/SauleStarter/Startup.cs#L13

**Comment by barsh** [comment]
@joukevandermaas Like this
```
config.ConfigureJsonApi();
```

See https://github.com/barsh/SauleStarter/blob/master/SauleStarter/Startup.cs#L13

**Comment by barsh** [comment]
@joukevandermaas can you point me towards any documentation or provide sample code on overloading the `ConfigureJsonApi` method so that Json Api responses are sent back to Chrome?

**Comment by joukevandermaas** [comment]
I guess it would be `config.ConfigureJsonApi(new JsonApiConfiguration(), overwriteOtherFormatters: true)`.

**Comment by barsh** [comment]
@joukevandermaas thanks, that did the trick!
